Merge PR #712: Show usage when incorrect number of CLI args provided
Prior to this change, using an incorrect number of arguments would show
a not-very-helpful error message like:

Error: accepts 3 arg(s), received 2

Now, also include the command's usage after that error message, so the
user doesn't have to re-run the command with --help to figure out what
they've missed.

Also adjust the usage lines to only use square brackets when indicating
an optional argument, as recommended by POSIX Utility Conventions and
the cobra documentation for Command. Also prefer underscores rather than
hyphens for parameter names per POSIX.

Co-authored-by: Justin Tieri <37750742+jtieri@users.noreply.github.com>